# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chippendales' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chippendales

  target 'ChippendalesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Chippmoji' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chippmoji
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end

target 'Chippmojistickers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chippmojistickers

end
